### ISSUE TITLE
[feature request] Allow Liquid Balance advertising as a configurable option

### ISSUE THREAD

**Issue by Impa10r** [ElementsProject/peerswap#278] opened 2024-01-22 16:15 UTC
Liquid peerswappers have problem finding peers with enough Liquid balance to initiate swap outs. They resort to sharing screens in telegram groups, which is not efficient. It would be better if a user could allow including his L-BTC balance in gossip, so that it is shown in listpeers outputs. Could be a general option, or enabled on a per peer basis. Can be further fine tuned to advertise only starting from a certain threshold, limit at Max and round down to the nearest 0.5mln, for example. BTC amounts available for swapping can be advertised in a similar fashion.

**Comment by grubles** [comment] 2024-01-23 17:32
Duplicate of #272

**Closed** 2024-05-01 12:03 UTC
Labels: feature request, liquid
